export const SONGS = {
  LOAD: 'SONGS_LOAD',
  LOAD_SUCCESS: 'SONGS_LOAD_SUCCESS',
}

export const SONG = {
  LOAD: 'SONG_LOAD',
  LOAD_SUCCESS: 'SONG_LOAD_SUCCESS',
}

export const ALBUM = {
  LOAD: 'ALBUM_LOAD',
  LOAD_SUCCESS: 'ALBUM_LOAD_SUCCESS',
}

export const STATUS = {
  PLAY_LIST_STATUS: 'PLAY_LIST_STATUS',
  LOGIN: 'LOGIN_STATUS',
  CONTENT_CHANGE: 'CONTENT_CHANGE',
  MENU_NAME: 'MENU_NAME'
}

export const ERROR = "ERROR";

export const PLAY = "PLAY";